name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # 03:00 JST daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@7d95e7d4cdc028dd1e1cbd957d65f35efb12ae39 # v0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name stevenfukase
          git config user.email fukasesteven@gmail.com
          git add profile-3d-contrib/
          if git commit -m "generated" ; then
            git push
          fi
